export const WORDS = [
  { id: 101, word: "Manoel", tip: "Louquinho da cabeca" },
  { id: 1, word: "Leão", tip: "Rei da selva" },
  { id: 2, word: "Tigre", tip: "Grande felino listrado" },
  { id: 3, word: "Elefante", tip: "Maior mamífero terrestre" },
  { id: 4, word: "Girafa", tip: "Pescoço longo" },
  { id: 5, word: "Zebra", tip: "Cavalo listrado" },
  { id: 6, word: "Cavalo", tip: "Usado em corridas e fazendas" },
  { id: 7, word: "Vaca", tip: "Fornece leite" },
  { id: 8, word: "Porco", tip: "Animal de criação que adora lama" },
  { id: 9, word: "Cachorro", tip: "Melhor amigo do homem" },
  { id: 10, word: "Gato", tip: "Doméstico, adora caçar ratos" },
  { id: 11, word: "Rato", tip: "Pequeno roedor" },
  {
    id: 12,
    word: "Coelho",
    tip: "Animal de orelhas grandes que adora cenouras",
  },
  { id: 13, word: "Raposa", tip: "Astuta e de cauda felpuda" },
  { id: 14, word: "Lobo", tip: "Parente selvagem do cachorro" },
  { id: 15, word: "Urso", tip: "Grande mamífero que hiberna" },
  { id: 16, word: "Panda", tip: "Urso que come bambu" },
  { id: 17, word: "Canguru", tip: "Carrega o filhote na bolsa" },
  { id: 18, word: "Koala", tip: "Animal australiano que dorme muito" },
  { id: 19, word: "Tatu", tip: "Possui casco rígido" },
  { id: 20, word: "Tamanduá", tip: "Se alimenta de formigas" },
  { id: 21, word: "Preguiça", tip: "Movimentos bem lentos" },
  { id: 22, word: "Onça", tip: "Felino típico da América do Sul" },
  { id: 23, word: "Jacaré", tip: "Reptil de água doce" },
  { id: 24, word: "Crocodilo", tip: "Reptil de água salgada e doce" },
  { id: 25, word: "Tartaruga", tip: "Carrega sua casa nas costas" },
  { id: 26, word: "Cágado", tip: "Semelhante à tartaruga, mas de água doce" },
  { id: 27, word: "Sapo", tip: "Amfíbio que adora pular" },
  { id: 28, word: "Rã", tip: "Amfíbio menor que o sapo" },
  {
    id: 29,
    word: "Peixe-palhaço",
    tip: "Popularizado pelo filme Procurando Nemo",
  },
  { id: 30, word: "Tubarão", tip: "Predador dos mares" },
  { id: 31, word: "Golfinho", tip: "Mamífero marinho muito inteligente" },
  { id: 32, word: "Baleia", tip: "O maior animal do planeta" },
  { id: 33, word: "Orca", tip: "Também chamada de baleia assassina" },
  { id: 34, word: "Pinguim", tip: "Ave que não voa e vive no gelo" },
  { id: 35, word: "Águia", tip: "Ave de rapina com visão aguçada" },
  { id: 36, word: "Falcão", tip: "Ave veloz e caçadora" },
  { id: 37, word: "Coruja", tip: "Ave noturna que gira a cabeça" },
  { id: 38, word: "Papagaio", tip: "Ave que imita a voz humana" },
  { id: 39, word: "Arara", tip: "Ave colorida da floresta tropical" },
  { id: 40, word: "Canário", tip: "Pássaro famoso pelo canto" },
  { id: 41, word: "Beija-flor", tip: "Ave que bate as asas muito rápido" },
  { id: 42, word: "Pato", tip: "Ave aquática que grasna" },
  { id: 43, word: "Ganso", tip: "Ave maior que o pato" },
  { id: 44, word: "Galinha", tip: "Ave doméstica que bota ovos" },
  { id: 45, word: "Galo", tip: "Canta ao amanhecer" },
  { id: 46, word: "Pavão", tip: "Ave com cauda em leque colorido" },
  { id: 47, word: "Cisne", tip: "Ave aquática elegante" },
  { id: 48, word: "Flamingo", tip: "Ave rosa que fica em uma perna só" },
  { id: 49, word: "Camelo", tip: "Resiste ao deserto com corcova" },
  {
    id: 50,
    word: "Dromedário",
    tip: "Parecido com o camelo, mas com uma corcova",
  },
  { id: 51, word: "Macaco", tip: "Animal que gosta de bananas" },
  { id: 52, word: "Gorila", tip: "Grande primata forte" },
  { id: 53, word: "Chimpanzé", tip: "Primata inteligente, parente do homem" },
  { id: 54, word: "Orangotango", tip: "Primata ruivo da Ásia" },
  { id: 55, word: "Camaleão", tip: "Muda de cor para se camuflar" },
  { id: 56, word: "Iguana", tip: "Réptil de aparência pré-histórica" },
  { id: 57, word: "Cobra", tip: "Réptil que rasteja e pode ser venenoso" },
  { id: 58, word: "Anaconda", tip: "Gigante das cobras" },
  { id: 59, word: "Jacutingas", tip: "Ave rara brasileira da Mata Atlântica" },
  { id: 60, word: "Arraia", tip: "Animal marinho achatado" },
  { id: 61, word: "Polvo", tip: "Molusco com oito braços" },
  { id: 62, word: "Lula", tip: "Semelhante ao polvo, mas com corpo alongado" },
  { id: 63, word: "Caranguejo", tip: "Animal de casco duro e pinças" },
  {
    id: 64,
    word: "Lagosta",
    tip: "Crustáceo de água salgada com grandes pinças",
  },
  { id: 65, word: "Camarão", tip: "Crustáceo pequeno usado em culinária" },
  {
    id: 66,
    word: "Borboleta",
    tip: "Inseto colorido que passa por metamorfose",
  },
  { id: 67, word: "Mariposa", tip: "Parecida com a borboleta, mas noturna" },
  { id: 68, word: "Abelha", tip: "Inseto que produz mel" },
  { id: 69, word: "Vespa", tip: "Inseto com ferrão doloroso" },
  { id: 70, word: "Formiga", tip: "Inseto trabalhador que vive em colônias" },
  { id: 71, word: "Besouro", tip: "Inseto de casco duro" },
  { id: 72, word: "Joaninha", tip: "Pequeno inseto vermelho com pintinhas" },
  { id: 73, word: "Grilo", tip: "Inseto que canta à noite" },
  { id: 74, word: "Gafanhoto", tip: "Inseto saltador que vive em grupos" },
  { id: 75, word: "Louva-a-deus", tip: "Inseto de aparência religiosa" },
  { id: 76, word: "Escorpião", tip: "Aracnídeo com cauda venenosa" },
  { id: 77, word: "Aranha", tip: "Constrói teias" },
  { id: 78, word: "Caracol", tip: "Carrega sua concha nas costas" },
  { id: 79, word: "Lesma", tip: "Parecida com o caracol, mas sem concha" },
  { id: 80, word: "Estrela-do-mar", tip: "Animal marinho com cinco braços" },
  { id: 81, word: "Ouriço-do-mar", tip: "Animal espinhoso do oceano" },
  { id: 82, word: "Medusa", tip: "Animal gelatinoso e urticante do mar" },
  { id: 83, word: "Cavalo-marinho", tip: "Peixe com forma curiosa" },
  { id: 84, word: "Morcego", tip: "Único mamífero que voa" },
  { id: 85, word: "Texugo", tip: "Animal escavador de hábitos noturnos" },
  { id: 86, word: "Lontra", tip: "Mamífero aquático brincalhão" },
  { id: 87, word: "Foca", tip: "Mamífero marinho que bate palmas" },
  {
    id: 88,
    word: "Leão-marinho",
    tip: "Parecido com a foca, mas com orelhas visíveis",
  },
  { id: 89, word: "Morsa", tip: "Possui grandes presas de marfim" },
  {
    id: 90,
    word: "Bicho-preguiça",
    tip: "Mamífero que vive pendurado em árvores",
  },
  { id: 91, word: "Cervo", tip: "Mamífero com galhadas" },
  { id: 92, word: "Alce", tip: "Parente do cervo, maior e com chifres largos" },
  { id: 93, word: "Rena", tip: "Puxa o trenó do Papai Noel" },
  { id: 94, word: "Cabra", tip: "Escaladora de montanhas" },
  { id: 95, word: "Ovelha", tip: "Animal que fornece lã" },
  { id: 96, word: "Burro", tip: "Parente do cavalo, muito teimoso" },
  { id: 97, word: "Lhama", tip: "Animal dos Andes, usado como carga" },
  { id: 98, word: "Alpaca", tip: "Parente da lhama, famosa pela lã macia" },
  { id: 99, word: "Hipopótamo", tip: "Mamífero gigante que vive em rios" },
  { id: 100, word: "Rinoceronte", tip: "Mamífero de grande chifre" },
]
